#!/usr/bin/env node
// Regenerates derived files from lib/themes.js:
//   docs/contrast.md   — the contrast audit (checked in, reviewed in PRs)
//   site/themes.json   — theme data (all themes, with their audit numbers)
//   site/index.html    — the homepage's theme chips and counts (between <!-- themes:* --> markers)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { THEMES, GROUPS, audit, themesExport } from '../lib/themes.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const out = (rel, text) => {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log('wrote', rel);
};

const rows = THEMES.map((t) => ({ t, a: audit(t) }));
const line = ({ t, a }) =>
  `| ${t.name} | \`${t.id}\` | ${t.mode} | ${a.text}:1 | ${a.rating}${a.harsh ? ' · very high' : ''} | ${a.tintedText}:1 | ${Math.round(a.claudeKeep * 100)}%${a.claudeFriendly ? ' ✓' : ''} | ${a.claudeWorst}:1 ${a.claudeRole} | ${a.minAccent}:1 | ${a.lowAccents.join(', ') || '—'} |`;

const md = [
  '# Theme contrast audit',
  '',
  'Generated by `npm run export` from `lib/themes.js`. Ratios are WCAG 2.x contrast.',
  '',
  '- **Text** — theme foreground on its background. Every theme is AA (4.5:1) or better; tests enforce it.',
  '- **Tinted text** — worst case over every session color at the *bold* tint. Tints keep OKLCH lightness,',
  '  and tabby shrinks a tint rather than let text read worse than the theme itself.',
  '- **Accents** — raw palette accent vs background. Accents below 3:1 are pale colors in light themes;',
  '  tabby darkens them automatically wherever they carry information (the cursor, ≥ 3:1) and lightens',
  '  island dots to ≥ 4:1 on black. Title markers are emoji and unaffected.',
  '- **Very high** (> 15:1) is flagged because maximum contrast can itself cause glare for some people.',
  '- **Claude UI** — Claude Code draws its own colored text (dim gray, suggestions, its orange, diff words)',
  '  in its dark palette on dark themes and its light palette on light ones. Those palettes are designed for a',
  '  black or white background, so lighter dark themes lose some of that contrast. The column shows how much',
  '  Claude keeps on this theme (worst role over every tint); ✓ marks themes that keep at least 80%, which',
  '  are the ones tabby\'s automatic theme variety picks from. Match Claude\'s theme (/theme) to the tabby',
  '  theme\'s mode: Claude\'s dark theme draws white text, which is unreadable on a light theme.',
  '',
  ...Object.entries(GROUPS).flatMap(([id, label]) => [
    `## ${label}`,
    '',
    '| Theme | id | mode | text | rating | tinted text | Claude UI kept | Claude worst | min accent | pale accents |',
    '|---|---|---|---|---|---|---|---|---|---|',
    ...rows.filter((r) => r.t.group === id).map(line),
    '',
  ]),
].join('\n');

out('docs/contrast.md', md);
out('site/themes.json', JSON.stringify(themesExport('tabby'), null, 0) + '\n');

// Homepage theme rail: a fixed selection, rendered as static chips (front: the theme; back: its audit).
const FEATURED = ['tabby', 'nord', 'ember', 'rose-pine', 'kanagawa', 'tokyo-night', 'catppuccin-mocha', 'everforest', 'midnight', 'gruvbox-material', 'flexoki', 'iceberg', 'oxocarbon', 'paper', 'mist', 'one-dark', 'night-owl', 'modus-vivendi'];
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const chip = (t) => {
  const a = audit(t);
  const acc = Object.values(t.accents).slice(0, 4);
  const claude = Math.round(a.claudeKeep * 100);
  return `      <li class="chip"><div class="chip-inner" tabindex="0" role="group" aria-label="${esc(t.name)}: text contrast ${a.text} to 1, ${a.rating}. Claude's own colors keep ${claude}% of their contrast.">
        <div class="chip-face chip-front" style="background:${t.bg}"><div class="chip-term" style="color:${t.fg}"><div><span style="color:${acc[1]}">❯</span> claude</div><div style="opacity:.75">Refactor auth</div><div class="chip-dots">${acc.map((c) => `<span style="background:${c}"></span>`).join('')}</div></div><div class="chip-meta"><strong>${esc(t.name)}</strong><code>bg ${t.bg}<br>text ${t.fg}</code></div></div>
        <div class="chip-face chip-back"><small>Contrast</small><dl><div><dt>Text</dt><dd>${a.text}:1</dd></div><div><dt>Rating</dt><dd>${a.rating}</dd></div><div><dt>Claude UI</dt><dd>${claude}%</dd></div><div><dt>Mode</dt><dd>${t.mode}</dd></div></dl><strong>${esc(t.name)}</strong></div>
      </div></li>`;
};
const indexFile = path.join(ROOT, 'site/index.html');
let index = fs.readFileSync(indexFile, 'utf8');
const put = (name, value) => {
  const re = new RegExp(`(<!-- ${name} -->)[\\s\\S]*?(<!-- /${name} -->)`);
  if (!re.test(index)) throw new Error(`site/index.html is missing <!-- ${name} --> markers`);
  index = index.replace(re, `$1${value}$2`);
};
put('themes:total', String(THEMES.length));
put('themes:aaa', String(THEMES.filter((t) => audit(t).rating === 'AAA').length));
put('themes:chips', '\n' + FEATURED.map((id) => THEMES.find((t) => t.id === id)).filter(Boolean).map(chip).join('\n') + '\n');
fs.writeFileSync(indexFile, index);
console.log('wrote site/index.html (theme chips)');
