#!/usr/bin/env node
// Regenerates derived files from lib/themes.js:
//   docs/contrast.md   — the contrast audit (checked in, reviewed in PRs)
//   site/themes.json   — theme data for the website gallery and demo
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { THEMES, GROUPS, audit, themesExport } from '../lib/themes.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const out = (rel, text) => {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log('wrote', rel);
};

const rows = THEMES.map((t) => ({ t, a: audit(t) }));
const line = ({ t, a }) =>
  `| ${t.name} | \`${t.id}\` | ${t.mode} | ${a.text}:1 | ${a.rating}${a.harsh ? ' · very high' : ''} | ${a.tintedText}:1 | ${a.minAccent}:1 | ${a.lowAccents.join(', ') || '—'} |`;

const md = [
  '# Theme contrast audit',
  '',
  'Generated by `npm run export` from `lib/themes.js`. Ratios are WCAG 2.x contrast.',
  '',
  '- **Text** — theme foreground on its background. Every theme is AA (4.5:1) or better; tests enforce it.',
  '- **Tinted text** — worst case over every session color at the *bold* tint. Tints keep OKLCH lightness,',
  '  and tabby shrinks a tint rather than let text read worse than the theme itself.',
  '- **Accents** — raw palette accent vs background. Accents below 3:1 are pale colors in light themes;',
  '  tabby darkens them automatically wherever they carry information (the cursor, ≥ 3:1) and lightens',
  '  island dots to ≥ 4:1 on black. Title markers are emoji and unaffected.',
  '- **Very high** (> 15:1) is flagged because maximum contrast can itself cause glare for some people.',
  '',
  ...Object.entries(GROUPS).flatMap(([id, label]) => [
    `## ${label}`,
    '',
    '| Theme | id | mode | text | rating | tinted text | min accent | pale accents |',
    '|---|---|---|---|---|---|---|---|',
    ...rows.filter((r) => r.t.group === id).map(line),
    '',
  ]),
].join('\n');

out('docs/contrast.md', md);
out('site/themes.json', JSON.stringify(themesExport('tabby'), null, 0) + '\n');
